saidam017

medium

# Calls to inactive vault's  `pushTotalUnderlyingToController()` cause rebalance process to stuck

## Summary

While rebalancing,  calls to inactive vault's `pushTotalUnderlyingToController()` can create mismatch between `vaultStage[_vaultNumber].underlyingReceived` and `vaultStage[_vaultNumber].activeVaults` value, this causing calls to `pushVaultAmounts()`  will reverts and rebalance process to stuck.

or it could reach `vaultStage[_vaultNumber].underlyingReceived` equal `vaultStage[_vaultNumber].activeVaults` and proccess further without using correct vault, and eventually will make rebalance process to stuck.

## Vulnerability Detail

Possibility 1 :
call `pushTotalUnderlyingToController()` inside `MainVault.sol` will eventually call `setTotalUnderlying()` inside `XChainController.sol ` and increment `vaultStage[_vaultNumber].underlyingReceived++` without checking if the vault is active or not. This will lead to `vaultStage[_vaultNumber].underlyingReceived` value not equal to `vaultStage[_vaultNumber].activeVaults`, if all active vault also calls `pushTotalUnderlyingToController()` .

 `pushVaultAmounts()` can't be called because `vaultStage[_vaultNumber].underlyingReceived` and `vaultStage[_vaultNumber].activeVaults` value is not equal, which is required inside `onlyWhenUnderlyingsReceived` modifier.

Possibility 2 : 

Inactive vault's `pushTotalUnderlyingToController()`  call  could cause  `vaultStage[_vaultNumber].underlyingReceived` to equal `vaultStage[_vaultNumber].activeVaults` without calling `pushTotalUnderlyingToController()` inside the denied active vault.

And can deliberately or accidently call  `pushVaultAmounts()` and `rebalanceXChain()`, but eventually will stuck in the process of calling `sendFundsToVault()`, since `vaultStage[_vaultNumber].fundsReceived` not equal to `vaultStage[_vaultNumber].activeVaults`. Leaving the rebalance process in the bad state.


## PoC

Scenario Possibility 1: 
rebalance reach the  `pushTotalUnderlyingToController()` process. Vault is available on 4 chain, the 4th vault already set to inactive. User can deliberately or accidently call  inactive vault's `pushTotalUnderlyingToController()`.  causing `vaultStage[_vaultNumber].underlyingReceived` = 4 while `vaultStage[_vaultNumber].activeVaults` = 3. Now `pushVaultAmounts()` can't be called to further process rebalance.

```javascript
 it('3) Trigger vaults to push totalUnderlyings to xChainController (modified)', async function () {
    await vault1.connect(user).deposit(100_000 * 1e6, userAddr);
    await vault2.connect(user).deposit(200_000 * 1e6, userAddr);

    await vault2.setExchangeRateTEST(1.2 * 1e6);
    await vault2.connect(user).withdrawalRequest(50_000 * 1e6);

    await vault1.pushTotalUnderlyingToController({ value: parseEther('0.1') });
    await vault2.pushTotalUnderlyingToController({ value: parseEther('0.1') });
    await vault3.pushTotalUnderlyingToController({ value: parseEther('0.1') });
    // this vault is already set inactive
    await vault4.pushTotalUnderlyingToController({ value: parseEther('0.1') });

    let activeVaults = await xChainController.getActiveVaultState(vaultNumber);
    console.log(`active vaults : ${activeVaults}`);
    let num = await xChainController.getUnderlyingState(vaultNumber);
    console.log(`underlying received : ${num}`); 

    //  Should revert 

    const chainIds = await xChainController.getChainIds();
    for (let chain of chainIds) {
      await expect(xChainController.pushVaultAmounts(vaultNumber, chain, {
        value: parseEther('0.1'),
      })).to.be.revertedWith('Not all underlyings received');
    }

  });
```

Scenario Possibility 2: 
rebalance reach the  `pushTotalUnderlyingToController()` process. Vault is available on 4 chain, the 4th vault already set to inactive. User can deliberately or accidently call  inactive vault's `pushTotalUnderlyingToController()`.  causing `vaultStage[_vaultNumber].underlyingReceived` = 3 equal to `vaultStage[_vaultNumber].activeVaults` = 3, without calling one of the correct active vault's `pushTotalUnderlyingToController()` .

## Impact

Possibility 1:
this condition (`vaultStage[_vaultNumber].underlyingReceived == vaultStage[_vaultNumber].activeVaults`) is required for `pushVaultAmounts()` call, not meeting this condition causing rebalance process to stuck.

Possibility 2:
condition (`vaultStage[_vaultNumber].underlyingReceived == vaultStage[_vaultNumber].activeVaults`) meet and `pushVaultAmounts()` can be processed without the processing the correct vault, but eventually rebalance process will stuck in the process of calling `sendFundsToVault()`, since `vaultStage[_vaultNumber].fundsReceived` not equal to `vaultStage[_vaultNumber].activeVaults`. Leaving the rebalance process in the bad state.

## Code Snippet

https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/MainVault.sol#L249-L273
https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/XProvider.sol#L214-L245
https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/XChainController.sol#L258-L267
https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/XChainController.sol#L276-L289


## Tool used

Manual Review

## Recommendation

Consider to check if vault is active or not before increment `vaultStage[_vaultNumber].underlyingReceived` value.

```solidity
  function setTotalUnderlyingInt(
    uint256 _vaultNumber,
    uint32 _chainId,
    uint256 _underlying,
    uint256 _totalSupply,
    uint256 _withdrawalRequests
  ) internal {
    vaults[_vaultNumber].totalUnderlyingPerChain[_chainId] = _underlying;
    vaults[_vaultNumber].withdrawalRequests[_chainId] = _withdrawalRequests;
    vaults[_vaultNumber].totalSupply += _totalSupply;
    vaults[_vaultNumber].totalUnderlying += _underlying;
    vaults[_vaultNumber].totalWithdrawalRequests += _withdrawalRequests;
    if (!getVaultChainIdOff(_vaultNumber, _chainId)) {
       vaultStage[_vaultNumber].underlyingReceived++;
    }
  }
```
